version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    restart: always

  frontend:
    build: ./covid-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: always

  test:
    build: ./backend
    command: python -m unittest tests/test_app.py
    depends_on:
      - backend